---
to: content/posts/<%= category %>/<%= permalink %>.md
---
---
title: <%= title %>
description: '<%= description %>'
image: <%= image %>
author: <%= author %>
category: <%= category %>
createdAt: <%= new Date().toISOString() %>
---

# This is a heading
This content is autogenerated. Please, open your editor and write an awesome blog post.
